### ISSUE TITLE
SSL Handshake failure on MacOS

### ISSUE THREAD

**Issue by bilalunalnet** [aniliyidogan/screm.co#2]
When i try to connect to screm.co I get a SSL Handshake error. I reproduced the error on another macOS. I think it caused by the SSL Certificate, or it may be related to macOS only. 
Here is my specs;
macOS Sierra(Verison 10.12.16)
Chrome 66
Firefox 60.0.2

**Comment by abdvel** [comment]
+1

**Comment by aniliyidogan** [comment]
Thanks this issue. SSL will be active today. I'm working on it.

**Comment by aniliyidogan** [comment]
Now https://screm.co 💯
